setwd("/Users/guruprasadvijendra/datasciencecoursera/EDA-Week1")
df <- read.table("household_power_consumption 2.txt",header = TRUE, sep = ";", stringsAsFactors = FALSE, dec = ".")
dfsubset <- df[df$Date %in% c("1/2/2007","2/2/2007"),]
timeperiod <- strptime(paste(dfsubset$Date,dfsubset$Time,sep=" "), "%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2))
plot(timeperiod,dfsubset$Global_active_power,type="l",ylab = "Global Active Power", xlab=" ")
plot(timeperiod,dfsubset$Voltage,type="l",ylab = "Voltage")
plot(timeperiod,dfsubset$Sub_metering_1,col="gray",type="l",ylab = "Energy Sub Metering",xlab = " ")
points(timeperiod,dfsubset$Sub_metering_2,col="red",type="l")
points(timeperiod,dfsubset$Sub_metering_3,col="blue",type="l")
plot(timeperiod,dfsubset$Global_reactive_power,type="l",ylab = "Global Reactive Power")